services:
  - type: web
    name: warehouse-backend
    env: go
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    rootDir: backend
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: warehouse-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_BASE
        value: https://warehouse-backend.onrender.com/api  # use your actual backend URL
